learning_templates/basic_app/urls.py
from django.urls import path,include
from django.contrib import admin
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('relative', views.relative, name='relative'),
    path('other', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text' : 'Hello World', 'number' : 100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">OTHER</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:relative' %}">Relative</a></li>
        </ul>

      </div>

    </nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
  {% block body_block %}


    <h1>Welcome to Index</h1>
    <h2>This is Index.html</h2>
    {{ text|cut:'ello' }}
    {{ number|add:"21" }}
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>Welcome to Other</h1>
    <h2> Template Inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1> Welcome to Relative Url Templates</h1>
    <a href="{% url 'basic_app:other' %}"> The Other Way</a>
    <a href="{% url 'admin:index' %}">The Admin Way</a>
    <a href="{% url 'index' %}"> Home Page</a>
  {% endblock %}